# Generated by Django 5.1.1 on 2024-09-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopadminaccount',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
