# Generated by Django 5.1.1 on 2024-10-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0002_shopadminaccount_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopadminaccount',
            name='display_id',
            field=models.IntegerField(editable=False, null=True, unique=True),
        ),
    ]
