# Generated by Django 5.1.1 on 2024-09-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_authentication', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopadminaccount',
            options={'permissions': [('can_add_product', 'Can add products'), ('can_edit_product', 'Can edit products'), ('can_delete_product', 'Can delete products')]},
        ),
        migrations.AlterField(
            model_name='shopadminaccount',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='shop_admin_account_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='shopadminaccount',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='shop_admin_account_set', to='auth.permission'),
        ),
    ]
