# Generated by Django 5.1.1 on 2024-09-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_authentication', '0002_alter_shopadminaccount_options_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopadminaccount',
            options={},
        ),
        migrations.AlterField(
            model_name='shopadminaccount',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='shop_admin_accounts', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='shopadminaccount',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='shop_admin_accounts', to='auth.permission'),
        ),
    ]
