# Generated by Django 5.1.1 on 2024-09-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_authentication', '0003_alter_shopadminaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopadminaccount',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
