# Generated by Django 5.1.1 on 2024-10-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_shop', '0003_alter_order_shipping_address_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_id',
            field=models.IntegerField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='display_id',
            field=models.IntegerField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='display_id',
            field=models.IntegerField(editable=False, null=True, unique=True),
        ),
    ]
