# Generated by Django 5.1.1 on 2024-10-06 04:38

from django.db import migrations

def set_display_ids(apps, schema_editor):
    Order = apps.get_model('practice_shop', 'Order')
    Product = apps.get_model('practice_shop', 'Product')
    Category = apps.get_model('practice_shop', 'Category')

    for idx, order in enumerate(Order.objects.all(), start=1):
        order.display_id = f'{idx}'  # Adjust the format as needed
        order.save()

    for idx, product in enumerate(Product.objects.all(), start=1):
        product.display_id = f'{idx}'  # Adjust the format as needed
        product.save()

    for idx, category in enumerate(Category.objects.all(), start=1):
        category.display_id = f'{idx}'  # Adjust the format as needed
        category.save()

class Migration(migrations.Migration):

    dependencies = [
        ('practice_shop', '0004_category_display_id_order_display_id_and_more'),  # Update with the last migration
    ]

    operations = [
        migrations.RunPython(set_display_ids),
    ]
